services:
  mythosquest:
    build: .
    container_name: mythosquest_ai
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env  # Loads API key from .env file
    stdin_open: true
    tty: true
    command: ["python", "ai_dm.py"]
