services:
  mythosquest:
    build: .
    container_name: mythosquest_ai
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=ai_dm.py
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: ["python", "ai_dm.py"]

volumes:
  db_data: