services:
  mythosquest:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mythosquest.rule=Host(`mythosquest.bittygpt.com`)"
      - "traefik.http.routers.mythosquest.entrypoints=websecure"
      - "traefik.http.routers.mythosquest.tls.certresolver=letsencrypt"
      - "traefik.http.services.mythosquest.loadbalancer.server.port=5000"
    restart: always
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
